export default actionTypes = {
  ADD_EXERCISE: 'ADD_EXERCISE',
  ADD_EXERCISE_TEMPLATE: 'ADD_EXERCISE_TEMPLATE',
  ADD_WORKOUT_TEMPLATE: 'ADD_WORKOUT_TEMPLATE',
  REMOVE_EXERCISE: 'REMOVE_EXERCISE',
  REMOVE_EXERCISE_TEMPLATE: 'REMOVE_EXERCISE_TEMPLATE',
  REMOVE_WORKOUT_TEMPLATE: 'REMOVE_WORKOUT_TEMPLATE',
  RECEIVE_EXERCISES: 'RECEIVE_EXERCISES',
  RECEIVE_EXERCISE_TEMPLATES: 'RECEIVE_EXERCISE_TEMPLATES',
  RECEIVE_SIGN_IN: 'RECEIVE_SIGN_IN',
  RECEIVE_SIGN_OUT: 'RECEIVE_SIGN_OUT',
  RECEIVE_WORKOUT_TEMPLATES: 'RECEIVE_WORKOUT_TEMPLATES',
  REQUEST_EXERCISES: 'REQUEST_EXERCISES',
  REQUEST_EXERCISE_TEMPLATES: 'REQUEST_EXERCISE_TEMPLATES',
  REQUEST_SIGN_IN: 'REQUEST_SIGN_IN',
  REQUEST_SIGN_OUT: 'REQUEST_SIGN_OUT',
  REQUEST_WORKOUT_TEMPLATES: 'REQUEST_WORKOUT_TEMPLATES',
  TOUCH_AUTH: 'TOUCH_AUTH'
};
